### ISSUE TITLE
maybe exchange should have 4 buttons

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp.me#52]
|  | download | ingest |
| --- | --- | --- |
| images |  |  |
| graphs |  |  |

@willgray @j6k4m8 what do you guys think?

**Comment by wrgr** [comment]
what about:

download  upload  (maybe clearer than ingest - people upload data, we
ingest it)

images
data derivatives

or

images
annotations
graphs

Best,
Will

On Sat, Aug 22, 2015 at 5:56 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
isn't the way they upload/download images vs. annotations the same?
meaning that a link for either would go to the same place?
if not, then i support.

**Comment by wrgr** [comment]
I'll talk with Kunal this week - assign this to me.  Currently I think
image ingest is a distinct process.  Mainly because "ingest" doesn't deal
with RAMON-type metadata.  I don't know if his services can support paint
or not.  The underlying HDF5 queries are very similar, although different
datatypes...

Best,
Will

On Sat, Aug 22, 2015 at 6:24 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
i'm happy with download & upload.

annotations are images with metadata, 
graphs are not images.

**Comment by wrgr** [comment]
Ok, let me take a shot at this.  Agree we need images and graphs.  Maybe
something in-between.  We might also think of images, metadata, and
graphs.  I'll play and try something out.
